// --- MAPA DE URLS Y LÓGICA DE ENLACES PARA LAS 54 PARASHOT (hatanakh.com) ---

const PARASHAT_URLS = {
    "Bereshit": "https://www.hatanakh.com/es?biblia=0.0.0&bibliaTo=0.5.7&parasha=Bereshit",
    "Noach": "https://www.hatanakh.com/es?biblia=0.5.8&bibliaTo=0.10.31&parasha=Noaj",
    "Nóaj": "https://www.hatanakh.com/es?biblia=0.5.8&bibliaTo=0.10.31&parasha=Noaj",
    "Lech-Lecha": "https://www.hatanakh.com/es?biblia=0.11.0&bibliaTo=0.16.26&parasha=Lej%20Leja",
    "Lej Lejá": "https://www.hatanakh.com/es?biblia=0.11.0&bibliaTo=0.16.26&parasha=Lej%20Leja",
    "Vayera": "https://www.hatanakh.com/es?biblia=0.17.0&bibliaTo=0.21.23&parasha=Vayera",
    "Vayerá": "https://www.hatanakh.com/es?biblia=0.17.0&bibliaTo=0.21.23&parasha=Vayera",
    "Chayei Sara": "https://www.hatanakh.com/es?biblia=0.22.0&bibliaTo=0.24.17&parasha=Jayei%20Sarah",
    "Jayé Sará": "https://www.hatanakh.com/es?biblia=0.22.0&bibliaTo=0.24.17&parasha=Jayei%20Sarah",
    "Toldot": "https://www.hatanakh.com/es?biblia=0.24.18&bibliaTo=0.27.8&parasha=Toldot",
    "Toledot": "https://www.hatanakh.com/es?biblia=0.24.18&bibliaTo=0.27.8&parasha=Toldot",
    "Vayetzei": "https://www.hatanakh.com/es?biblia=0.27.9&bibliaTo=0.31.2&parasha=Vayetze",
    "Vayetzé": "https://www.hatanakh.com/es?biblia=0.27.9&bibliaTo=0.31.2&parasha=Vayetze",
    "Vayishlach": "https://www.hatanakh.com/es?biblia=0.31.3&bibliaTo=0.35.42&parasha=Vayishlaj",
    "Vayishlaj": "https://www.hatanakh.com/es?biblia=0.31.3&bibliaTo=0.35.42&parasha=Vayishlaj",
    "Vayeshev": "https://www.hatanakh.com/es?biblia=0.36.0&bibliaTo=0.39.22&parasha=Vayeshev",
    "Vayéshev": "https://www.hatanakh.com/es?biblia=0.36.0&bibliaTo=0.39.22&parasha=Vayeshev",
    "Miketz": "https://www.hatanakh.com/es?biblia=0.40.0&bibliaTo=0.43.16&parasha=Miketz",
    "Vayigash": "https://www.hatanakh.com/es?biblia=0.43.17&bibliaTo=0.46.26&parasha=Vayigash",
    "Vayechi": "https://www.hatanakh.com/es?biblia=0.46.27&bibliaTo=0.49.25&parasha=Vayeji",
    "Vayejí": "https://www.hatanakh.com/es?biblia=0.46.27&bibliaTo=0.49.25&parasha=Vayeji",
    "Shemot": "https://www.hatanakh.com/es?biblia=1.0.0&bibliaTo=1.5.0&parasha=Shmot",
    "Vaera": "https://www.hatanakh.com/es?biblia=1.5.1&bibliaTo=1.8.34&parasha=Va'era",
    "Vaerá": "https://www.hatanakh.com/es?biblia=1.5.1&bibliaTo=1.8.34&parasha=Va'era",
    "Bo": "https://www.hatanakh.com/es?biblia=1.9.0&bibliaTo=1.12.15&parasha=Bo",
    "Beshalach": "https://www.hatanakh.com/es?biblia=1.12.16&bibliaTo=1.16.15&parasha=Beshalaj",
    "Beshalaj": "https://www.hatanakh.com/es?biblia=1.12.16&bibliaTo=1.16.15&parasha=Beshalaj",
    "Yitro": "https://www.hatanakh.com/es?biblia=1.17.0&bibliaTo=1.19.22&parasha=Yitro",
    "Yitró": "https://www.hatanakh.com/es?biblia=1.17.0&bibliaTo=1.19.22&parasha=Yitro",
    "Mishpatim": "https://www.hatanakh.com/es?biblia=1.20.0&bibliaTo=1.23.17&parasha=Mishpatim",
    "Terumah": "https://www.hatanakh.com/es?biblia=1.24.0&bibliaTo=1.26.18&parasha=Terumah",
    "Terumá": "https://www.hatanakh.com/es?biblia=1.24.0&bibliaTo=1.26.18&parasha=Terumah",
    "Tetzaveh": "https://www.hatanakh.com/es?biblia=1.26.19&bibliaTo=1.29.9&parasha=Tetzaveh",
    "Tetzavé": "https://www.hatanakh.com/es?biblia=1.26.19&bibliaTo=1.29.9&parasha=Tetzaveh",
    "Ki Tisa": "https://www.hatanakh.com/es?biblia=1.29.10&bibliaTo=1.33.34&parasha=Ki%20Tisa",
    "Ki Tisá": "https://www.hatanakh.com/es?biblia=1.29.10&bibliaTo=1.33.34&parasha=Ki%20Tisa",
    "Vayakhel": "https://www.hatanakh.com/es?biblia=1.34.0&bibliaTo=1.37.19&parasha=Vayakhel",
    "Pekudei": "https://www.hatanakh.com/es?biblia=1.37.20&bibliaTo=1.39.37&parasha=Pekudey",
    "Vayikra": "https://www.hatanakh.com/es?biblia=2.0.0&bibliaTo=2.4.25&parasha=Vayikra",
    "Vayikrá": "https://www.hatanakh.com/es?biblia=2.0.0&bibliaTo=2.4.25&parasha=Vayikra",
    "Tzav": "https://www.hatanakh.com/es?biblia=2.5.0&bibliaTo=2.7.35&parasha=Tzav",
    "Shmini": "https://www.hatanakh.com/es?biblia=2.8.0&bibliaTo=2.10.46&parasha=Shemini",
    "Sheminí": "https://www.hatanakh.com/es?biblia=2.8.0&bibliaTo=2.10.46&parasha=Shemini",
    "Tazria": "https://www.hatanakh.com/es?biblia=2.11.0&bibliaTo=2.12.58&parasha=Tazria",
    "Tazría": "https://www.hatanakh.com/es?biblia=2.11.0&bibliaTo=2.12.58&parasha=Tazria",
    "Metzora": "https://www.hatanakh.com/es?biblia=2.13.0&bibliaTo=2.14.32&parasha=Metzora",
    "Metzorá": "https://www.hatanakh.com/es?biblia=2.13.0&bibliaTo=2.14.32&parasha=Metzora",
    "Achrei Mot": "https://www.hatanakh.com/es?biblia=2.15.0&bibliaTo=2.17.29&parasha=Ajarei%20Mot",
    "Ajarei Mot": "https://www.hatanakh.com/es?biblia=2.15.0&bibliaTo=2.17.29&parasha=Ajarei%20Mot",
    "Kedoshim": "https://www.hatanakh.com/es?biblia=2.18.0&bibliaTo=2.19.26&parasha=Kedoshim",
    "Emor": "https://www.hatanakh.com/es?biblia=2.20.0&bibliaTo=2.23.22&parasha=Emor",
    "Behar": "https://www.hatanakh.com/es?biblia=2.24.0&bibliaTo=2.25.1&parasha=Behar",
    "Bechukotai": "https://www.hatanakh.com/es?biblia=2.25.2&bibliaTo=2.26.33&parasha=Bejukotai",
    "Bejukotai": "https://www.hatanakh.com/es?biblia=2.25.2&bibliaTo=2.26.33&parasha=Bejukotai",
    "Bamidbar": "https://www.hatanakh.com/es?biblia=3.0.0&bibliaTo=3.3.19&parasha=Bamidbar",
    "Nasso": "https://www.hatanakh.com/es?biblia=3.3.20&bibliaTo=3.6.88&parasha=Naso",
    "Nasó": "https://www.hatanakh.com/es?biblia=3.3.20&bibliaTo=3.6.88&parasha=Naso",
    "Beha'alotcha": "https://www.hatanakh.com/es?biblia=3.7.0&bibliaTo=3.11.15&parasha=Beha'aloteja",
    "Beha’alotcha": "https://www.hatanakh.com/es?biblia=3.7.0&bibliaTo=3.11.15&parasha=Beha'aloteja",
    "Beha'alotja": "https://www.hatanakh.com/es?biblia=3.7.0&bibliaTo=3.11.15&parasha=Beha'aloteja",
    "Beha’alotja": "https://www.hatanakh.com/es?biblia=3.7.0&bibliaTo=3.11.15&parasha=Beha'aloteja",
    "Beha'alotjá": "https://www.hatanakh.com/es?biblia=3.7.0&bibliaTo=3.11.15&parasha=Beha'aloteja",
    "Beha’alotjá": "https://www.hatanakh.com/es?biblia=3.7.0&bibliaTo=3.11.15&parasha=Beha'aloteja",
    "Sh'lach": "https://www.hatanakh.com/es?biblia=3.12.0&bibliaTo=3.14.40&parasha=Shelaj%20Leja",
    "Sh’lach": "https://www.hatanakh.com/es?biblia=3.12.0&bibliaTo=3.14.40&parasha=Shelaj%20Leja",
    "Sh'laj": "https://www.hatanakh.com/es?biblia=3.12.0&bibliaTo=3.14.40&parasha=Shelaj%20Leja",
    "Sh’laj": "https://www.hatanakh.com/es?biblia=3.12.0&bibliaTo=3.14.40&parasha=Shelaj%20Leja",
    "Shlaj": "https://www.hatanakh.com/es?biblia=3.12.0&bibliaTo=3.14.40&parasha=Shelaj%20Leja",
    "Shelaj": "https://www.hatanakh.com/es?biblia=3.12.0&bibliaTo=3.14.40&parasha=Shelaj%20Leja",
    "Korach": "https://www.hatanakh.com/es?biblia=3.15.0&bibliaTo=3.17.31&parasha=Koraj",
    "Kóraj": "https://www.hatanakh.com/es?biblia=3.15.0&bibliaTo=3.17.31&parasha=Koraj",
    "Chukat": "https://www.hatanakh.com/es?biblia=3.18.0&bibliaTo=3.21.0&parasha=Jukat",
    "Jukat": "https://www.hatanakh.com/es?biblia=3.18.0&bibliaTo=3.21.0&parasha=Jukat",
    "Balak": "https://www.hatanakh.com/es?biblia=3.21.1&bibliaTo=3.24.8&parasha=Balak",
    "Pinchas": "https://www.hatanakh.com/es?biblia=3.24.9&bibliaTo=3.29.0&parasha=Pinjas",
    "Pinjas": "https://www.hatanakh.com/es?biblia=3.24.9&bibliaTo=3.29.0&parasha=Pinjas",
    "Matot": "https://www.hatanakh.com/es?biblia=3.29.1&bibliaTo=3.31.41&parasha=Matot",
    "Masei": "https://www.hatanakh.com/es?biblia=3.32.0&bibliaTo=3.35.12&parasha=Masa'ei",
    "Devarim": "https://www.hatanakh.com/es?biblia=4.0.0&bibliaTo=4.2.21&parasha=Devarim",
    "Va'etchanan": "https://www.hatanakh.com/es?biblia=4.2.22&bibliaTo=4.6.10&parasha=Vaetjanan",
    "Vaetjanán": "https://www.hatanakh.com/es?biblia=4.2.22&bibliaTo=4.6.10&parasha=Vaetjanan",
    "Vaetjanan": "https://www.hatanakh.com/es?biblia=4.2.22&bibliaTo=4.6.10&parasha=Vaetjanan",
    "Eikev": "https://www.hatanakh.com/es?biblia=4.6.11&bibliaTo=4.10.24&parasha=hekev",
    "Ekev": "https://www.hatanakh.com/es?biblia=4.6.11&bibliaTo=4.10.24&parasha=hekev",
    "Re'eh": "https://www.hatanakh.com/es?biblia=4.10.25&bibliaTo=4.15.16&parasha=Re'eh",
    "Re’eh": "https://www.hatanakh.com/es?biblia=4.10.25&bibliaTo=4.15.16&parasha=Re'eh",
    "Re'éh": "https://www.hatanakh.com/es?biblia=4.10.25&bibliaTo=4.15.16&parasha=Re'eh",
    "Re’éh": "https://www.hatanakh.com/es?biblia=4.10.25&bibliaTo=4.15.16&parasha=Re'eh",
    "Reeh": "https://www.hatanakh.com/es?biblia=4.10.25&bibliaTo=4.15.16&parasha=Re'eh",
    "Shoftim": "https://www.hatanakh.com/es?biblia=4.15.17&bibliaTo=4.20.8&parasha=Shoftim",
    "Ki Teitzei": "https://www.hatanakh.com/es?biblia=4.20.9&bibliaTo=4.24.18&parasha=Ki%20Tetze",
    "Ki Tetzé": "https://www.hatanakh.com/es?biblia=4.20.9&bibliaTo=4.24.18&parasha=Ki%20Tetze",
    "Ki Tavo": "https://www.hatanakh.com/es?biblia=4.25.0&bibliaTo=4.28.7&parasha=Ki%20Tavo",
    "Ki Tavó": "https://www.hatanakh.com/es?biblia=4.25.0&bibliaTo=4.28.7&parasha=Ki%20Tavo",
    "Nitzavim": "https://www.hatanakh.com/es?biblia=4.28.8&bibliaTo=4.29.19&parasha=Nitzavim",
    "Vayeilech": "https://www.hatanakh.com/es?biblia=4.30.0&bibliaTo=4.30.29&parasha=Vayelej",
    "Vayélej": "https://www.hatanakh.com/es?biblia=4.30.0&bibliaTo=4.30.29&parasha=Vayelej",
    "Ha'Azinu": "https://www.hatanakh.com/es?biblia=4.31.0&bibliaTo=4.31.51&parasha=Haazinu",
    "Ha’Azinu": "https://www.hatanakh.com/es?biblia=4.31.0&bibliaTo=4.31.51&parasha=Haazinu",
    "Ha'azinu": "https://www.hatanakh.com/es?biblia=4.31.0&bibliaTo=4.31.51&parasha=Haazinu",
    "Ha’azinu": "https://www.hatanakh.com/es?biblia=4.31.0&bibliaTo=4.31.51&parasha=Haazinu",
    "Haazinu": "https://www.hatanakh.com/es?biblia=4.31.0&bibliaTo=4.31.51&parasha=Haazinu",
    "V'Zot HaBerachah": "https://www.hatanakh.com/es?biblia=4.32.0&bibliaTo=4.33.11&parasha=Vezot%20Haberajah",
    "Vezot Haberajá": "https://www.hatanakh.com/es?biblia=4.32.0&bibliaTo=4.33.11&parasha=Vezot%20Haberajah"
};

const DISPLAY_NAMES = {
    "Bereshit": "Bereshit", "Noach": "Nóaj", "Nóaj": "Nóaj", "Lech-Lecha": "Lej Lejá", "Lej Lejá": "Lej Lejá",
    "Vayera": "Vayerá", "Vayerá": "Vayerá", "Chayei Sara": "Jayé Sará", "Jayé Sará": "Jayé Sará",
    "Toldot": "Toledot", "Toledot": "Toledot", "Vayetzei": "Vayetzé", "Vayetzé": "Vayetzé",
    "Vayishlach": "Vayishlaj", "Vayishlaj": "Vayishlaj", "Vayeshev": "Vayéshev", "Vayéshev": "Vayéshev",
    "Miketz": "Miketz", "Vayigash": "Vayigash", "Vayechi": "Vayejí", "Vayejí": "Vayejí",
    "Shemot": "Shemot", "Vaera": "Vaerá", "Vaerá": "Vaerá", "Bo": "Bo",
    "Beshalach": "Beshalaj", "Beshalaj": "Beshalaj", "Yitro": "Yitró", "Yitró": "Yitró",
    "Mishpatim": "Mishpatim", "Terumah": "Terumá", "Terumá": "Terumá", "Tetzaveh": "Tetzavé", "Tetzavé": "Tetzavé",
    "Ki Tisa": "Ki Tisá", "Ki Tisá": "Ki Tisá", "Vayakhel": "Vayakhel", "Pekudei": "Pekudei",
    "Vayikra": "Vayikrá", "Vayikrá": "Vayikrá", "Tzav": "Tzav", "Shmini": "Sheminí", "Sheminí": "Sheminí",
    "Tazria": "Tazría", "Tazría": "Tazría", "Metzora": "Metzorá", "Metzorá": "Metzorá",
    "Achrei Mot": "Ajarei Mot", "Ajarei Mot": "Ajarei Mot", "Kedoshim": "Kedoshim", "Emor": "Emor",
    "Behar": "Behar", "Bechukotai": "Bejukotai", "Bejukotai": "Bejukotai", "Bamidbar": "Bamidbar",
    "Nasso": "Nasó", "Nasó": "Nasó",
    "Beha'alotcha": "Beha'alotjá", "Beha’alotcha": "Beha'alotjá", "Beha'alotja": "Beha'alotjá", "Beha’alotja": "Beha'alotjá",
    "Beha'alotjá": "Beha'alotjá", "Beha’alotjá": "Beha'alotjá",
    "Sh'lach": "Shlaj", "Sh’lach": "Shlaj", "Sh'laj": "Shlaj", "Sh’laj": "Shlaj", "Shlaj": "Shlaj", "Shelaj": "Shlaj",
    "Korach": "Kóraj", "Kóraj": "Kóraj",
    "Chukat": "Jukat", "Jukat": "Jukat", "Balak": "Balak", "Pinchas": "Pinjas", "Pinjas": "Pinjas",
    "Matot": "Matot", "Masei": "Masei", "Devarim": "Devarim", "Va'etchanan": "Vaetjanán", "Vaetjanán": "Vaetjanán", "Vaetjanan": "Vaetjanán",
    "Eikev": "Ekev", "Ekev": "Ekev",
    "Re'eh": "Re'éh", "Re’eh": "Re'éh", "Re'éh": "Re'éh", "Re’éh": "Re'éh", "Reeh": "Re'éh",
    "Shoftim": "Shoftim",
    "Ki Teitzei": "Ki Tetzé", "Ki Tetzé": "Ki Tetzé", "Ki Tavo": "Ki Tavó", "Ki Tavó": "Ki Tavó",
    "Nitzavim": "Nitzavim", "Vayeilech": "Vayélej", "Vayélej": "Vayélej",
    "Ha'Azinu": "Ha'azinu", "Ha’Azinu": "Ha'azinu", "Ha'azinu": "Ha'azinu", "Ha’azinu": "Ha'azinu", "Haazinu": "Ha'azinu",
    "V'Zot HaBerachah": "Vezot Haberajá", "Vezot Haberajá": "Vezot Haberajá"
};

const MESES_HEBREOS_ES = {
    'Nisan': 'Nisán', 'Iyar': 'Iyar', 'Sivan': 'Siván', 'Tamuz': 'Tamuz',
    'Av': 'Av', 'Elul': 'Elul', 'Tishrei': 'Tishrei', 'Cheshvan': 'Jeshván',
    'Kislev': 'Kislev', 'Tevet': 'Tevet', "Sh'vat": 'Shevat', 'Adar': 'Adar',
    'Adar I': 'Adar I', 'Adar II': 'Adar II'
};
